### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by pluff** [shemerey/atom-tt#2]
[Enter steps to reproduce below:]

1. install the package
2. select a text in a non-editor
3. push cmd+ctrl+\

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.4
**Thrown From**: [atom-tt](https://github.com/shemerey/atom-tt) package, v0.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /Users/shutin/.atom/packages/atom-tt/lib/atom-tt.coffee:44

TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.AtomTt.toggle (/Users/shutin/.atom/packages/atom-tt/lib/atom-tt.coffee:44:53)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-tt:toggle (/Users/shutin/.atom/packages/atom-tt/lib/atom-tt.coffee:22:82)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:00.9.0 atom-tt:toggle (div.panels-item)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ruby": [
        "*.arb"
      ]
    },
    "disabledPackages": [
      "symbols-view",
      "package-cop"
    ],
    "packagesWithKeymapsDisabled": [
      "ruby-test",
      "ruby-block",
      "atom-beautify",
      "linter"
    ],
    "projectHome": "/Users/shutin/www"
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.5.2
atom-tt, v0.4.0
autocomplete-ruby, v0.1.0
cucumber, v0.5.0
file-icons, v1.7.14
language-diff, v0.4.0
language-haml, v0.24.0
language-rspec, v0.5.0
language-slim, v0.5.0
linter, v1.11.8
linter-rubocop, v0.4.7
linter-slim, v1.0.0
merge-conflicts, v1.4.4
react, v0.15.0
topnet, v0.0.3
tree-view-bundler, v0.0.3

# Dev
No dev packages
```

**Comment by shemerey** [comment]
fixed in `v0.5`
